---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles
      etcd-dependencies:
        # Define patterns to include dependencies in the group
        applies-to: version-updates
        patterns:
          - "*"  # Matches all dependencies in the package ecosystem

  - package-ecosystem: gomod
    directory: /tools/mod  # Not linked from /go.mod
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles
      tools-dependencies:
        # Define patterns to include dependencies in the group
        applies-to: version-updates
        patterns:
          - "*"  # Matches all dependencies in the package ecosystem

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.4"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.5"
    schedule:
      interval: monthly
